### ISSUE TITLE
Javascript SDK not detecting user logged in using parseFacebookUserSession

### ISSUE THREAD

**Issue by sujayjaju** [ParsePlatform/parse-facebook-user-session#7]
The following code
```javascript
Parse.initialize("key...","key...");
var currentUser = Parse.User.current();
```
When run after logging in a user using "parse-facebook-user-session.js", sets the currentUser as "null"

Is there a way for the cloud code to communicate the current facebook user session to the javascript SDK?

**Comment by gfosco** [comment]
What do you mean by "run after".. Please explain more of the scenario, where the user is logged in, what the flow is, etc.

**Comment by sujayjaju** [comment]
The workflow:
* We use parse-facebook-user-session to log the user in using facebook
* Within the Express Routes in the CloudCode, Parse.User.current() returns the user correctly.
* When we go to a page that uses the Javascript SDK, i.e.
```javascript
Parse.initialize("key...","key...");
var currentUser = Parse.User.current();
```
  * currentUser is null

Please let me know if you need more info...

**Comment by gfosco** [comment]
Ah.. yeah, so this is not a feature provided by this middleware.  If you also want to log the user in on the client-side, you should hit a route to get the sessionToken for the user, and user Parse.User.become().

**Comment by jmiller-sc** [comment]
Thanks for the info...

**Comment by grantespo** [comment]
"Hit a route to get the sessionToken" How do you do this?
